### ISSUE TITLE
PDFだけreleaseできないか

### ISSUE THREAD

**Issue by ttrace** [ttrace/bunko-galley-action#1]
Github Actionsの`actions/upload-release-asset@v1.0.1`ではプロジェクト全体がアップロードされてしまう。
成果物のPDFだけアップロードする方法がないだろうか。

**Comment by keiji** [comment]
`actions/upload-release-asset` はarchivedになっていて、すでに開発は止まっているようです。

[softprops/action-gh-release](https://github.com/softprops/action-gh-release) であれば、`with.files`でファイルを限定できそうですが、こちらで代替できませんか。

https://github.com/softprops/action-gh-release#%EF%B8%8F-uploading-release-assets

**Comment by ttrace** [comment]
ありがとうございます。たしかに行けそうです！

**Comment by ttrace** [comment]
with.filesでファイルだけ指定した場合も、プロジェクト全体がアップロードされてしまいました。
Github pagesあたりと繋がないと難しいかもしれません。

**Comment by ttrace** [comment]
とりあえずオープンにしたまま残しておきます。

**Comment by keiji** [comment]
あ、Releaseに`Source code(zip)`と`Source code(tar.gz)`が含まれるという話でしょうか。
GitHubの仕様上tagを作ると必ずこの２つが作成されてReleaseにも含まれるので、GitHub Actions自体は期待通り動いていると考えます。

https://github.com/ttrace/bunko-galley-action/releases/tag/galley-pdf

**Comment by ttrace** [comment]
なるほど、わかりました。PDFだけアップロードするには、tag.ref以外のきっかけを作った方がいいわけですね。
ではissueをクローズします。
